# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      
    environment:
      DEPLOY_BRANCH: gh-pages
      USER_EMAIL: tyxchen@outlook.com
      USER_NAME: Terry Chen


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Configure git
          command: |
            git config user.email "$USER_EMAIL"
            git config user.name "$USER_NAME"

      - run:
          name: Delete previous deploy branch, if it exists
          command: |
            if [ `git branch | grep $DEPLOY_BRANCH` ]; then
                git branch -D $DEPLOY_BRANCH
            fi

      - run:
          name: Create new deploy branch
          command: |
            git checkout --orphan $DEPLOY_BRANCH

      - run:
          name: Build
          command: |
            npx webpack

      - run:
          name: Delete files
          command: |
            find . -maxdepth 1 \
                ! -name '.git' ! -name '.gitignore' ! -name 'build' \
                ! -name '.circleci' ! -name '.' \
                -exec rm -rf {} \;
    
      - run:
          name: Tell GitHub Pages to not process with Jekyll
          command: |
            touch .nojekyll

      - run:
          name: Add assets
          command: |
            git add -A .
            git add -f build/
            git commit -m "assets $CIRCLE_SHA1"

      - run:
          name: Push to deploy
          command: |
            git push -f origin $DEPLOY_BRANCH

      - run:
          name: Cleanup
          command: |
            git checkout master
            git branch -D $DEPLOY_BRANCH

